### ISSUE TITLE
Possible function error ?

### ISSUE THREAD

**Issue by ethen8181** [WinVector/zmPDSwR#5]
Hi, sorry for bothering you. I have a small question regarding to the function for calculating the squared distance between two vectors on [Chapter 8](https://github.com/WinVector/zmPDSwR/blob/master/CodeExamples/c08_Unsupervised_methods/00143_example_8.7_of_section_8.1.3.R). 

In the book the function is :

sqr_edist <- function(x, y) { 
       sum((x-y)^2)
}

but don't you need to square root it after the calculation. so it'll be like :

sqr_edist <- function(x, y) { 
       sqrt( sum( (x-y)^2 ) )
}

Thanks for helping out.

**Comment by NinaZumel** [comment]
Hi Ethen:

In the book, we are actually deliberately computing sum of squares (not root mean squared error) because that was the relevant measure for this computation. RMSE is not additive in the way sum of squared error is. Both sum of squared error and root mean square error are used by statisticians in different places.

Regards,
Nina

--------------------
Nina Zumel
Win-Vector, LLC
http://www.win-vector.com/ <http://www.win-vector.com/>
http://www.win-vector.com/blog/ <http://www.win-vector.com/blog/>
Our book: Practical Data Science with R http://www.manning.com/zumel/ <http://www.manning.com/zumel/>
Twitter: https://twitter.com/WinVectorLLC <https://twitter.com/WinVectorLLC>
nzumel@win-vector.com <mailto:nzumel@win-vector.com>

**Comment by ethen8181** [comment]
Hi Nina,

Thanks for replying back so fast. So the sum of squares is used here because we're calculating the variance?

If true, then for the assigning new points to the cluster [section](https://github.com/WinVector/zmPDSwR/blob/master/CodeExamples/c08_Unsupervised_methods/00149_example_8.13_of_section_8.1.5.R). When we're calculating how far the new data point is from each clusters' center. Why are we still using the squared euclidean distance instead of normal euclidean distance? Aren't we just calculating the "distance"? (Or is it because here calculating euclidean distance or squared euclidean distance doesn't affect the ordering ).

Best,
Ethen

**Comment by NinaZumel** [comment]
Yes. We use the sum of squares when we are interested in variance-like measures. And we can use still squared distance without square-rooting it when determining cluster centers because not square-rooting doesn’t affect the order, and it saves us a computation.

Cheers,
Nina

--------------------
Nina Zumel
Win-Vector, LLC
http://www.win-vector.com/ <http://www.win-vector.com/>
http://www.win-vector.com/blog/ <http://www.win-vector.com/blog/>
Our book: Practical Data Science with R http://www.manning.com/zumel/ <http://www.manning.com/zumel/>
Twitter: https://twitter.com/WinVectorLLC <https://twitter.com/WinVectorLLC>
nzumel@win-vector.com <mailto:nzumel@win-vector.com>

**Comment by JohnMount** [comment]
Think of it this way. sqrt() is a monotone transformation- so deciding which cluster center is closest is the same for squared distance or standard distance (sqrt of squared distance).  So as sum of squares is a more common (and additive variance) measure we can forgo taking sqrt.

**Comment by ethen8181** [comment]
Thank you both for the clear response! Still going through the content, learned quite a lot so far! kudos for putting together the book.

Best Regards,
Ethen
